version: '3.7'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  unirate:
    container_name: unirate
    build: ./app/.
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app:/app
    
volumes:
  db_data: